## Feature Engineering
##### Relationship Between the Random variables:

  - X:height of a student
  - Y:Weight of a student
  - find is there any relationship between X and Y?
  - Class---->taken --->student--->

  - X increases---->y increses?
  - X increases---->Y decreases?
* we have a three measures for this
1. co-variance
2. Pearsen coefficient of correlation
3. spearmens rank correlations

In [2]:
import numpy as np

## 1. co-variance:

   - somewhat similar to variance
   - if we have two RV X and Y and we find the covariance by changing the measures then the covariance will change this is drawback of covariance
   - This is solved using Pearson coefficient of correlation
   - corelation doesn't imply the causation
   -  X and Y -------> RV
   -  corr(X,Y)----->it doesn't mean that X causes Y or Y causes X


In [4]:
height=np.array([140,145,160,155,165,170])
weight=np.array([45,48,50,56,60,65])
cv=np.cov(height,weight)
cv      #it gives covariance matrix

array([[134.16666667,  80.        ],
       [ 80.        ,  58.8       ]])

In [11]:
cv[0,1]

80.0

In [25]:
height_inch=height*0.4
weight_inch=weight*2.2
cv2=np.cov(height_inch,weight_inch)
cv2

array([[ 21.46666667,  70.4       ],
       [ 70.4       , 284.592     ]])

### 2. Pearsons coefficient of correlation:

  - rho=cov(x,y)/sd(x)*sd(y)
  - np.corrcoef(x,y)
  - Pearson coefficient of correlation will work good when the relationship is linear
  - if the relationship is non linear then the value of rho is 0

In [14]:
rho=np.corrcoef(height,weight)
rho

array([[1.        , 0.90069761],
       [0.90069761, 1.        ]])

### 3. Spearmen rank correlation

   - let we have two random variable X and Y from this two random variable we are creating the new random variable and we will find the pearsons coefficient of correlation for new random variable
   -  Syntax: from scipy.stats as stats import spearmanr
   -  rho = spearmanr(x,y) 

In [8]:
from scipy.stats import spearmanr 

In [9]:
import scipy.stats as stats

In [10]:
rho=spearmanr(height,weight)
rho

SignificanceResult(statistic=0.942857142857143, pvalue=0.004804664723032055)