### @NumPy:Numerical Python
    -it is an array
    -it is core python library
    -we are using NumPy to perform the complex operation
    -complex operations we are performing with the help of NumPy
    -NumPy is extension to the multi-dimensional array
    -array is a collection of homogenous/similar kind of data.
    -it is open source and freeware
       open source: code is available for everyone 
       freeware: no cost
    -NumPy is written in python + c

@ 1.performing the operation on higher dimensional array---complex operation
      
    In a machine learning each feature as a dimensional
  
     scalar: only magnitude 
         ex: displacement

     vector: magnitude as well as dimension

@ Data visualization:

     dimensionality reduction: PCA, TSNE
  
@ 2.Complex matrix multiplication:
  
    1D:vector
    2D:matrix
    3D:cube
    nD: tensors

    a. matrix multiplication: costly/complex
        -because of the vectorization numpy perform the multiplication in a faster way
  
    b. Inverse 
    c. Rank
    d. Transpose
    e. eigen values and eigen vectors
    f. determinant

*@ Linear Expression:
  
    a1x+b1y+c=0
    a2x+b2y+c=0
      a. simultaneous equation
      b. inversion, reduction---matrix
      c. LPP: simplex method

@ 3.Numerical method and optimization:
   
    -In a mathematics we have two kinds of method:
        a. Analytical method:Algorithm
           -if we have a formulation, method, theorem or axioms to solve a particular problem then we called it as analytical method
   
        b. Numerical method:procedure
            -approximation
             ex: newton Raphson,etc

        c. Numerical integration:
       
@ 4.Scientific computing

@ 5.vector computing

@ 6.Statical operation
  
    statistics: way of solving the problem with the help of data

*@ for using the numpy we need to import it
  
    syntax:
       import numpy as np

     import---keyword
     numpy---library name
     no--alias

*@ why we are using alias? 
  
    -it will increase the readablity


In [23]:
import numpy as np

### *creating numpy array:

### @ 1. np.array():
     
         -we are creating the numpy array manually with the help of np.array()
         -it will always take list as a argument
         -numpy is a fixed size
     
         Syntax:
            identifier/variable=np.array([e1,e2---])
        
         ex:
           array([23,45,67,89,99])---1D--vector
 
         -number of subscript operator will decide the dimension of numpy array
              []---1D
            [[]]---2D
         -ndim:will gives the dimension of the numpy array
         syntax:
           array_name.ndim
          ex:
             array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])------matrix---2D(rows and columns)

          ex:
             array([[[1, 2],
                    [3, 4]],

                    [[5, 6],
                    [7, 8]]])-----cube---3D(length, height, width)


In [8]:
array1=np.array([23,45,67,89,99])
array1

array([23, 45, 67, 89, 99])

In [10]:
type(array1)

numpy.ndarray

In [14]:
array1.ndim

1

In [18]:
array2=np.array([[1,2,3,4],[5,6,7,8]])
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
array2.ndim

2

In [26]:
array3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
array3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [28]:
array3.ndim

3

In [9]:
import numpy as np

### @ 2. Creating NumPy array using arrange():

    -we are creating the numpy array by specifying the values in the arguments
     Syntax:
        np.arange(start,end,step_size)
       -by default it is starting from 0
       -by default step size is 1


### @difference between list and NumPy array:

    list:
       -collection of heterogeneous items
       -list is a variable size
       -list is not memory efficient because for one item it is creating two blocks of memory
       -so we required every time one block extra memory for each item
       -whenever we are storing the list in the memory ,the item will be stored wherever the space is available in the memory.
       -matrix operations are slow in list
       -to perform the matrix operation in list we have to iterate it becoz of that time and space both are getting increase

    numpy:
       -collection of similar kind of data items
       -it is of fixed size
       -numpy array will be stored inside the memory in a consecutive manner
       -so it is memory efficient
       -numpy is more closer to the hardware 
       -numpy is faster than list becoz it will follows the spatial or temporal aspect of cache
       -it is possible because of consecutive storing behaviour of numpy
       
#aspects of cache:

      spatial:instead of loading one block load the consecutive block also
      temporal aspect:instead of loading consecutive block load the entire array
      -matrix operations are faster in numpy because of vectorization.
      -in case of numpy array we don't need to iterate the matrix so it efficient
      -numpy will provide matrix multiplication in two ways
        1.element wise multiplication
        2.dot product

     scalar: magnitude
     vector: magnitude as well as direction


In [11]:
array4=np.arange(10)
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
array5=np.arange(10,30)
array5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [15]:
array6=np.arange(10,20,3)
array6

array([10, 13, 16, 19])

In [17]:
a=[[1,2],[3,4]]
b=[[3,4],[5,6]]
c=[[0,0],[0,0]]
for i in range(len(a)):
    for j in range(len(b)): 
        c[i][j]=a[i][j]+b[i][j]
print(c)        

[[4, 6], [8, 10]]


In [19]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[3,4],[5,6]])
a1+a2

array([[ 4,  6],
       [ 8, 10]])

In [21]:
a=[[1,2],[3,4]]
b=[[3,4],[5,6]]
c=[[0,0],[0,0]]
for i in range(len(a)):
    for j in range(len(b)):
        for k in range(len(b)):
            c[i][j]+=a[i][k]*b[k][j]
print(c)

[[13, 16], [29, 36]]


In [23]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[3,4],[5,6]])
a1*a2

array([[ 3,  8],
       [15, 24]])

In [25]:
a1.dot(a2)

array([[13, 16],
       [29, 36]])

### @ 3.creating numpy array using np.zeros()

    -it will create the numpy array with all elements zeros
    -if we are giving the order of a matrix as a argument then we have to give it in the form of tuple
      arr1=np.zeros(5)
      arr2=np.zeros((3,3))
    -zero matrix we called it as initialization matrix

In [27]:
arr1=np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [29]:
arr2=np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### @ 4.creating numpy array using np.ones()
    
    -it will create numpy array with all elemnets one
    -if we are giving the order of a matrix as a argument then we have to give it in the form of tuple


In [31]:
arr3=np.ones(5)
arr3

array([1., 1., 1., 1., 1.])

In [33]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### @ 5. creating numpy array using np.eye()
   - it will make all the principal diagonal elements 1 
   - arr7=np.eye(2,3)
   - arr5=np.eye(3,3)
   - arr6=np.eye(4)

In [35]:
arr5=np.eye(3,3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
arr6=np.eye(4)
arr6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
arr7=np.eye(2,3)
arr7

array([[1., 0., 0.],
       [0., 1., 0.]])

### @ 6.creating numpy array using np.diag()
    
    -it will create the diagonal matrix
    -it will always takes the argument in the form of list
    -d1=np.diag([1,2,3])
    -for creating the matrix of the combinations of zeros and ones ,we have to create it manually



In [44]:
d1=np.diag([1,2,3])
d1

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [46]:
d2=2*np.ones((3,3))
d2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [53]:
import numpy as np

### @ 7.creating numpy array using np.linspace():

    -it is used to create 1D numpy array (vector)
    -it will create the values as per the limit
    -and if we are not specifying the equidistant points by default it will take 50 points
    syntax:
      np.linspace(start,end,no_equi_points)
    -for samplings (when we don't have the proper sampling points)

### @ 8.np.random.rand():

    -it will create the random values array as per the limit according to the uniform distribution
    -uniform distribution: each values has equally likely chance of getting selected
    -it will take all the values less than or equal to zero becoz probability should not be grater than 1

In [10]:
r=np.random.rand(5)
r

array([0.93516236, 0.43911315, 0.29110991, 0.75631607, 0.45929232])

In [16]:
r1=np.random.rand(3,3)
r1

array([[0.69571464, 0.9299228 , 0.57692206],
       [0.89371238, 0.91806659, 0.83721499],
       [0.56760843, 0.62444465, 0.68917383]])

### @ 9.np.random.randn():

    -it will also gives the random values as per the standard normal variate(standard normal distribution)



In [18]:
r2=np.random.randn(5)
r2

array([-0.14160051, -0.6075353 ,  1.97634778,  0.82192138,  0.00724244])

### @ 10.np.random.randint():

    -it will generate the numpy array with any random values as per the range
    -np.random.randint(start,end,no_of_elements)



In [20]:
r3=np.random.randint(10,20,5)
r3

array([19, 16, 15, 12, 19])

In [22]:
r4=np.random.randint(10,20,(3,3))
r4

array([[16, 14, 18],
       [18, 12, 13],
       [13, 15, 11]])

### @11.copy():
     -it will copy the elements from one array to another array

In [24]:
a1=np.array([1,2,3,4,5])
a2=a1.copy()
a2

array([1, 2, 3, 4, 5])

In [26]:
z=np.array([1,2,3,4,5])
z.shape

(5,)

In [34]:
z.dtype

dtype('int32')

In [36]:
z.itemsize

4

## @ NumPy class are having the attribute:

* 1.ndim:it will give the dimension of the numpy array
* 2.shape: it will gives the order of the array
* 3.size:no.of elements present in the array
* 4.itemsize:how much memory each element of the array is occupying
* 5.dtype:it will give the datatype of the array
* 6.astype():it is use for typecasting


* 1.trace:

      sum of the diagonal elements of the array
      syntax:np.trace(array_name)

* 2.transpose of a matrix:

      -converting the rows of matrix into columns into row
      syntax:array

* 3.Inverse of matrix:
  
      -it will give the inverse of the matrix
      Syntax: np.linalg.inv(p)

* 4.Determinant:

      Syntax: np.linalg.det(a)

* 5.rank:

      -it will gives the rank of matrix
      -on of linearly independent rows and columns in the matrix 
      -np.linalg.matrix_rank(a)

* 6.scalar 


In [38]:
list1=[[1,2],[4,5]]
trace=0
for i in range(len(list1)):
    for j in range(len(list1)):
        if i==j:
            trace+=list1[i][j]
print(trace)

6


In [40]:
p=np.array([[1,2],[4,5]])
np.trace(p)

6

In [42]:
p.T

array([[1, 4],
       [2, 5]])

In [46]:
np.linalg.inv(p)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [52]:
np.linalg.det(p)

-2.9999999999999996

In [50]:
a=np.array([[1,2,3,4,5],[3,4,5,6,7],[4,5,6,7,8]])
np.linalg.matrix_rank(a)

2

In [54]:
a=np.array([1,2,3,4,5])
a+1

array([2, 3, 4, 5, 6])

In [56]:
a-1

array([0, 1, 2, 3, 4])

In [58]:
a*2

array([ 2,  4,  6,  8, 10])

In [60]:
a**2

array([ 1,  4,  9, 16, 25])

In [2]:
s="NaReSh";
s1="";
for i in s:
    if(ord(i)<96):
        s1=s1+chr(ord(i)+32)
    else:
        s1=s1+chr(ord(i)-32)
print(s1)

nArEsH


In [4]:
import numpy as np

### @ arithmatic operations on numpy:

* 1.addition(+)
* 2.subtraction(-)
* 3.multiplication(*)
* 4.division(/)
* 5.floor division(//)
* 6.power(*)
* 7.modulus(%)

      -all the arithmatic operation done by element wise


### @ 3.Scalar Operations on numpy array:

    -we are performing the operation with the help of scalar

### @ 4.Relational operations:

    -it is used to find the relation between the elements of the numpy array
    -<,>,==,!=,>=,<=---it will compare elementwise

     Syntax: np.array_equal(p1,p2)----it will compare arraywise

### @ 5.Logical operations on numpy:

    -all():it will return true value when all the elements in the array are true
       -every non-zero is considered as true

    -any():
     -it will true if atleast one value is true otherwise false 
    -logical_or
    -logical_and



In [6]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [8]:
a-b

array([-4, -4, -4, -4])

In [10]:
a**b

array([    1,    64,  2187, 65536])

In [12]:
a%b

array([1, 2, 3, 4])

In [14]:
a//b

array([0, 0, 0, 0])

In [16]:
a*b

array([ 5, 12, 21, 32])

In [18]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [28]:
a=np.ones((3,3))+1
a

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [30]:
a1=np.array([4,5,6,7,8])
a2=np.array([2,3,4,5,8])
a1>a2

array([ True,  True,  True,  True, False])

In [32]:
a1<a2

array([False, False, False, False, False])

In [34]:
a1==a2

array([False, False, False, False,  True])

In [36]:
a1!=a2

array([ True,  True,  True,  True, False])

In [40]:
c=np.array([[2,3],[4,5]])


In [48]:
p1=np.array([1,2,45,67])
p2=np.array([1,2,63,75])
p3=np.array([3,4,46,54])
np.array_equal(p1,p2)

False

In [50]:
np.array_equal(p1,p3)

False

In [52]:
s=np.array([1,0,3,4,5])
np.all(s)

False

In [54]:
np.any(s)

True

In [56]:
a=np.array([2,0,0,3,1])
b=np.array([4,5,0,0,56])
np.logical_or(a,b)

array([ True,  True, False,  True,  True])

In [58]:
np.logical_and(a,b)

array([ True, False, False, False,  True])

In [70]:
a=np.array([2,3,4,5,6])
np.log(a)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947])

In [68]:
np.exp(a)

array([  7.3890561 ,  20.08553692,  54.59815003, 148.4131591 ,
       403.42879349,   1.        ])

### @ 6.Transcendental operations:
    -when we have a log,exp(e),trigonometry----
    -np.log():it will give the log of each value present in numpy array
    -np.exp():it is giving the exponential value of each elements of numpy array
    -np.sin()  
    -np.cos()

In [72]:
a=np.array([3,4,5,6,30])
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 , -0.98803162])

In [74]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029,  0.15425145])

### @ 7.sorting:
    -np.sort():
         -it will sort in ascending order
         -it is not in-place sort

    -np.argsort():
         -it will perform the sorting on the basis of index of the numpy array
    
    -numpy_array.sort():it will perform inplace sorting 

* row-wise sorting:axis=1
* column-wise sorting :axis=0


In [76]:
a=([3,4,-5,-67,2,1])

In [84]:
b=np.sort(a)
print(a)
print(b)

[3, 4, -5, -67, 2, 1]
[-67  -5   1   2   3   4]


In [86]:
c=np.argsort(a)
c

array([3, 2, 5, 4, 0, 1], dtype=int64)

In [90]:
d=np.array([5,0,-1,-3,7,-14])
d.sort()
d

array([-14,  -3,  -1,   0,   5,   7])

In [92]:
mat1=np.array([[11,7,-2],[4,-6,17],[-23,18,-34]])
mat2=np.sort(mat1)
mat2

array([[ -2,   7,  11],
       [ -6,   4,  17],
       [-34, -23,  18]])

In [94]:
m3=np.argsort(mat1)
m3

array([[2, 1, 0],
       [1, 0, 2],
       [2, 0, 1]], dtype=int64)

In [98]:
mat1.sort()
mat1

array([[ -2,   7,  11],
       [ -6,   4,  17],
       [-34, -23,  18]])

In [102]:
n=np.array([[20,-11,-34],[22,-8,-99],[19,-19,12]])
n=np.sort(n,axis=0)
n

array([[ 19, -19, -99],
       [ 20, -11, -34],
       [ 22,  -8,  12]])

In [108]:
o=np.argsort(n,axis=0)
o

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [110]:
aa=np.array([34,-11,-22,17,79,90,-100])
rev_sorted=np.sort(aa)[::-1]
rev_sorted

array([  90,   79,   34,   17,  -11,  -22, -100])

### @8.aggregation operations:

* sum()
* max()
* min()
* argmax()
* argmin()


In [112]:
ab=np.array([3,4,5,6,7,8])
np.sum(ab)

33

In [114]:
np.max(ab)

8

In [116]:
np.min(ab)

3

In [118]:
np.argmin(ab)

0

In [120]:
np.argmax(ab)

5

In [2]:
import numpy as np

### @9.Searching in numpy array:

    1.np.where(condition):it will return the index of the elements where the condition is true

    2.np.nonzero():it will return the index of the non-zero elements in the array
       syntax: np.nonzero(array_name)

    3.np.extract():it will return the element besed on the condition
       syntax: np.extract(condition,array_name)



In [4]:
a=np.array([3,4,5,1,7])
np.where(a>2)

(array([0, 1, 2, 4], dtype=int64),)

In [8]:
np.where(a==2)

(array([], dtype=int64),)

In [10]:
np.where(a==3)

(array([0], dtype=int64),)

In [14]:
b=np.array([2,3,4,0,5,6,0,0])
np.nonzero(b)

(array([0, 1, 2, 4, 5], dtype=int64),)

In [18]:
c=np.array([4,5,6,11,19,20])
np.extract(c>5,c)

array([ 6, 11, 19, 20])

### @numpy is fixed length:

    * np.append():
       -it is used to add the lement in the numpy array 
       -it will not make changes directly in exicting array, we have to create a new array to see the changes
       -it is taking extra array for append
       syntax: np.append(array_element)

    * np.insert():
       -it will insert the element into numpy array at the particular position 
       -but to see the changes we have create another numpy array
       syntax: np,insert(array_name,index,item)

    * np.concatenate():
       -it is used to concatenate the numpy array to another numpy array
       -it will create a numpy array
        Syntax:np.concatenate((array_name,[i1,i2----]))


In [20]:
p=np.array([3,4,5,6,7])
np.append(p,45)

array([ 3,  4,  5,  6,  7, 45])

In [22]:
p

array([3, 4, 5, 6, 7])

In [24]:
q=np.array([3,4,5,6,7,8,9])
r=np.insert(q,2,100)
r

array([  3,   4, 100,   5,   6,   7,   8,   9])

In [32]:
d=np.array([45,67,89,90,100])
h=np.concatenate([d,[1,2,3,4]])
h

array([ 45,  67,  89,  90, 100,   1,   2,   3,   4])

### @10. reshaping:
    -it is converting the one numpy array into another dimensions
    Syntax:
      1. array_name=np.array([]).reshape(x_dim,y_dim)
      2.array_name.reshape()
    -number of elements before reshaping and after reshaping must be equal 

    -if only one row present in matrix:row vector:(1*n)
    -if only one column present in matrix:column vector:(n*1)

### @11.Accessing the elements of numpy array:
    -a. we can access the numpybelements using indexing


In [44]:
a1=np.array([0,0,0,0,0,0,0,1,0,0,0,0])
a1.shape

(12,)

In [48]:
a1.reshape(12,1)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0]])

In [50]:
a1.reshape(2,6)

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0]])

In [52]:
a1.reshape(2,2,3)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 1, 0],
        [0, 0, 0]]])

In [2]:
import numpy as np

In [4]:
a=np.array([2,3,4,5,6,7])
a[2]

4

In [10]:
b=np.array([[2,3],[4,5]])
b[1][0]

4

In [14]:
a1=np.arange(10)
a2=np.arange(5)
a1[5:]=a2[::-1]
a1

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [16]:
b1=np.array([2,3,4,5])
b2=np.array([1,2,3,4])
b3=np.array([2,3,4,5])
d=((b1<=b2)&(b1<=b3)).all()
d

False

In [2]:
import numpy as np

### @12. Statistics operation on numpy array :

* Statistics: R A Fisher
  
      -statistics is a way to solve a problem by using data
        1.descriptive statistics:
          -describing the data
          -we have different techniques and measures in descriptive stats to describe the data
          -we want to explore the data
  
          -statistics measures:
  
            first moment business decision (measures of central tendencies):
  
               1.mean:average of the data
                   mathematical notation: 
                      mean=(sum of all observation)/total number of observation
                   time:o(n)
                   -it is getting influenced by the outliers
                   -outliers:out of context value
                  Syntax: np.means(array_name)
                
               2.median:it will give the avarage
                   -when we have outlies present in the dataset the better to use median
                   -becoz median is not influenced by the outliers
                   formulation
                      a.no. of points are odd:
                         i.sort the datapoints
                        ii.middle element is means----O(nlogn)
                      b.no. of datapoints are even:
                         i.sort
                        ii.avg of mid element+(mid+1)element----O(nlogn)
                   Syntax: np.median(array_name)

               3.mode(scipy):
                     -it will work on the categorical data
                     -mode means maximum occurrence of the datapoints 
                     -there can be multiple modes in the dataset se called it as multimodal dataset
                     -if we wanted to select any one or two its completely depends upon problem statements
  
                   there is two types of data in statistics:
  
                     1.numerical data:
                        -it will contains the numerical value
                        -numerical data again classify into two types:
                           a. continuous data:it is having continuous real value 
                               ex:weight,height etc
                           b. discrete data: it will not contain fractional value
                               ex:count of student
                        -mean and medium will works on numerical data only
  
                      2.categorical data:
                        -it will specify the category
                        -we cannot find out the mean and median for categorical data

              second moment business decision: (measures of the dispersion)
  
                 -dispersion means how the data points are varying 
                  1.variance:
                    -how far each data point from the average
                    Syntax: np.var(array_name)
                  2.standard deviation:
                    -it is a square root of variance
                    Syntax: np.std(array_name)
                  3.range : max(array)
                         min(array)

            cumsum:
                [1,2,,4,5]:[1,3,6,10,15]
                Syntax: np.cumsum(array_name)

          Percentile :
             Syntax:np.percentile(array_name,value)

          co-relation:
             relationship between the two features
             rho:1----strong relation
                 0----no relation
                 -1----weak relation
             Syntax: np.corrcoef(a1,a1)

      2.inferential statistics
          -we are making some conclusion based on the sample and inferring about the population
          


In [4]:
a=np.array([3,4,5,6,7,8])
for i in a:
    print(i)

3
4
5
6
7
8


In [25]:
#13 iterate numpy array 
b=np.random.randint(10,30,(4,5)).reshape(5,4)
b

array([[18, 17, 19, 14],
       [12, 15, 13, 15],
       [13, 27, 24, 22],
       [26, 25, 19, 23],
       [24, 12, 20, 24]])

In [27]:
for i in range(len(b)):
    for j in range(len(b[0])):
        print(b[i][j])

18
17
19
14
12
15
13
15
13
27
24
22
26
25
19
23
24
12
20
24


In [29]:
#14 fancy indexing
b[[1,3]]

array([[12, 15, 13, 15],
       [26, 25, 19, 23]])

In [31]:
#15 boolean indexing/filtering
b>15

array([[ True,  True,  True, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True]])

In [20]:
f=(b>15)&(b%2==0)
f

array([[ True,  True, False,  True],
       [ True, False, False, False],
       [ True, False, False, False],
       [ True,  True, False, False],
       [ True, False, False, False]])

### @16.Brodcasting:
     -its ability to expand the array to perform the operations with the larger array
     -broadcasting is a process to perform the operation of small matrices and large matrix
     -with the help of this concept different size matrix operation can perform


In [22]:
#Broadcasting
aa=np.ones((3,3))+4
aa

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [24]:
a1=np.array([[2,3],[4,5]])
a2=np.array([1,2])

In [26]:
a2

array([1, 2])

In [28]:
a1

array([[2, 3],
       [4, 5]])

In [30]:
a1+a2

array([[3, 5],
       [5, 7]])

In [32]:
ab=np.arange(9).reshape(3,3)
ac=np.arange(3).reshape(3,1)
ab

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
ac

array([[0],
       [1],
       [2]])

In [36]:
ab+ac

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [54]:
ab1=np.arange(2).reshape(2,1)
ac1=np.arange(6).reshape(2,3)
ac1

array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
ab1

array([[0],
       [1]])

In [58]:
ab1+ac1

array([[0, 1, 2],
       [4, 5, 6]])

In [62]:
ab2=np.arange(3)[::-1].reshape(3,1)
ac2=np.arange(6).reshape(3,2)

In [64]:
ab2+ac2

array([[2, 3],
       [3, 4],
       [4, 5]])

In [2]:
import numpy as np

* why numpy is faster in that list
 it is closer to hardware and it is follow cache memory

* we  have 3D numpy array with random we need to add there array using loop

* RMO (Row measure order):
    np.reshape(array_name,dimension,'C')
  C-PL will follows the row major order

* CMO: column measure order
    np.reshape(array_name,dimension,'C')

  FORTRAN PL will follows CMO


In [4]:
a=np.random.randint(10,20,(3,3))
b=np.random.randint(5,8,(3,3))
a

array([[16, 19, 11],
       [14, 11, 16],
       [13, 16, 15]])

In [6]:
b

array([[6, 7, 5],
       [5, 5, 6],
       [7, 6, 5]])

In [8]:
a+b

array([[22, 26, 16],
       [19, 16, 22],
       [20, 22, 20]])

In [14]:
c=np.arange(9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.reshape(c,(1,9),'C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [20]:
np.reshape(c,(1,9),'F')

array([[0, 3, 6, 1, 4, 7, 2, 5, 8]])

### @concatenate two matrices:

    -np.concatenate([])
    -np.hstack([]):it will concatenate two matrices horizontally
    -np.vstack([]):it will concatenate two matrices vertically


In [18]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
np.concatenate([a1,a2])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [22]:
np.hstack([a1,a2])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [26]:
np.vstack([a1,a2])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### *** Copies and Views(important question in interview)
### @Copy():
    -when we use the copy(),it will create duplicate array with different buffer
    -the changes made in copied array will not affect the original array and vice versa
    -when we are using copy we required extra memory buffer so it is not memory efficient
    -when we are using copy() we have to stored the data as well as meta data

In [28]:
aa=np.array([1,2,3,4,5])
ab=aa.copy()
ab[1]=1000
print(aa)
print(ab)

[1 2 3 4 5]
[   1 1000    3    4    5]


### @View():

    -when we use view() it will not create the copy,it will create the view
    -both original array and views are at the same place
    -so we don't required extra buffer to store data
    -but we required to store the metadata to differentiate two array
    -so view() is memory efficient
    -by using the view() numpy will do the memory optimization
    -to check the both array at same space:
     Syntax: np.shares_memory(arr1,arr2)


In [32]:
aa1=np.array([5,6,7,8,9])
ab1=aa1.view()
aa1[0]=2000
print(aa1)
print(ab1)

[2000    6    7    8    9]
[2000    6    7    8    9]


In [36]:
np.shares_memory(aa1,ab1)


True

In [42]:
b=np.arange(9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### @flattening:
     -converting multidimensional array into single dimension
      Syntax: array_name.flatten()----it copy()---it is not memory efficient


In [44]:
c=b.flatten()
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### @ravel:
     - converting multidimensional array into single dimension
     Syntax: array_name.ravel()---it is view---it is memory efficient


In [48]:
d=b.ravel()
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### *reshaping is also copying so it is not memory efficient operation

In [50]:
e=np.zeros((3,2))
f=e.T.reshape(3,2)
f[0]=500

In [52]:
e

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [54]:
f

array([[500., 500.],
       [  0.,   0.],
       [  0.,   0.]])

In [56]:
s=np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
p=s[::2]
p

array([0, 2, 4, 6, 8])

In [60]:
np.shares_memory(s,p)

True

In [64]:
q=s[::2].copy()
q

array([0, 2, 4, 6, 8])

In [66]:
np.shares_memory(s,q)

False